### ISSUE TITLE
Streamline HA mode should be configured with HdfsFileStorage

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#687]
Right now ambari HDF streamline installation happens with LocalFileSystemStorage.

```
fileStorageConfiguration:
  className: "com.hortonworks.streamline.common.util.LocalFileSystemStorage"
  properties:
    directory: /grid/0/hdf/streamline/jar
``` 

If two or more streamline servers are running, the bootstrapped notifiers and udf jars will be available only in one of the hosts since the invocation of bootstrap from the second streamline server will fail with DuplicateEntityException.

Bootstrap should be run only from one of the hosts. Right now the bootstrap scripts are run multiple times from each streamline host and it can lead to race conditions or duplicate entity exceptions.
